name: chips
channels:
- bioconda
- conda-forge
- defaults
dependencies:
#GENERAL
- snakemake=5.4.5
- samtools>=1.8
- python>=3.5.2
- r=3.5.1
- numpy>=1.17.3
- pandas>=0.25.3

# adaptor trimming
- fastp=0.20.1

#align_*.snakefile
- bwa=0.7.15
- bowtie2=2.3.4.1
- sambamba=0.6.6
- picard=2.18.4
- bedtools=2.27.1 #for bamToFastq

#bam_snapshot
# - bioconductor-gviz

#meta aka ceas.snakefile

#conservation.snakefile
- pybigwig>=0.3.17

#contamination.snakefile

#fastqc.snakefile
- seqtk>=1.3
- fastqc>=0.11.5
- r-ggplot2>=2.2.0
- r-reshape2>=1.4.2

#frips.snakefile

#mapmaker.snakefile
- git
- ruamel.yaml

#motif_*.snakefile
- perl>=5.18.2
- homer>=4.7
- cython>=0.29.14
- jinja2>=2.10

#Tied to 2.8.2=3 b/c other updated versions produce missing seqlogo bin (homer)
- weblogo=2.8.2
- bioconductor-seqlogo>=1.46.0

#peaks.snakefile
- ucsc-bedgraphtobigwig>=332
- ucsc-bedsort>=332
- macs2>=2.2.6

#qdnaseq.snakefile
- bioconductor-qdnaseq>=1.18.0

#report.snakefile
- tabulate
- seaborn
- zip

#BUGS: minor missing
- r-r.utils

#report_example02.snakefile
- matplotlib =3.1.1
- intervaltree >=2.1.0
- future >=0.17.0
- hicmatrix >=15
- pysam >=0.14
- pytest
- pip
- gffutils >=0.9
- pybedtools >=0.8.1
- tqdm >=4.20
- multiqc
- plotly_express
- markdown
- pyyaml>=4
- pip:
    - "git+https://github.com/deeptools/pyGenomeTracks.git"
